### ISSUE TITLE
SQLite table/column initialization is not performed or described in the README.

### ISSUE THREAD

**Issue by markd315** [alanlekah/ethermine-ethereum-mining-tax-calculator#2]
I had issues using this script with sqlite3.

It seems totally unnecessary anyway, so suggested fix is in #1.

Here is my stacktrace if you care to investigate.
```
python calc.py
Namespace(feature=True)
Traceback (most recent call last):
  File "C:\Users\markd\ethermine\calc.py", line 67, in <module>
    main()
  File "C:\Users\markd\ethermine\calc.py", line 34, in main
    completed_hashes_cur = db_cur.execute("select hash from hashes")
sqlite3.OperationalError: no such table: hashes
```

**Comment by alanlekah** [comment]
Fixed in latest commit, thanks!
